# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy on Github Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy_on_ghpages:
    name: deploy on gh-pages
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - name: deploy on gh-pages
      run: |
            git config --global user.email "ansarinia@me.com"
            git config --global user.name "morteza"
            git remote set-url origin https://ce5c7878d3295c3725eb574c1c61dc88cfc7b25f@github.com/morteza/lens.git
            npm run deploy
      env:
        CI: false
